#ddev-generated
# If you remove the ddev-generated line above you
# are responsible for maintaining this file. DDEV will not then
# update it, for example if you add `additional_hostnames`, etc.

http:
  routers:
    twitty-web-80-http:
      entrypoints:
        - http-80
      rule: HostRegexp(`^twitty\.ddev\.site$`)
      
      service: "twitty-web-80"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "twitty-redirectHttps"
    twitty-web-8025-http:
      entrypoints:
        - http-8025
      rule: HostRegexp(`^twitty\.ddev\.site$`)
      
      service: "twitty-web-8025"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "twitty-redirectHttps"
    twitty-phpmyadmin-80-http:
      entrypoints:
        - http-8036
      rule: HostRegexp(`^twitty\.ddev\.site$`)
      
      service: "twitty-phpmyadmin-80"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "twitty-redirectHttps"
    
    
    
    twitty-web-80-https:
      entrypoints:
        - http-443
      rule: HostRegexp(`^twitty\.ddev\.site$`)
      
      service: "twitty-web-80"
      ruleSyntax: v3
      
      tls: true
      
    twitty-web-8025-https:
      entrypoints:
        - http-8026
      rule: HostRegexp(`^twitty\.ddev\.site$`)
      
      service: "twitty-web-8025"
      ruleSyntax: v3
      
      tls: true
      
    
    twitty-phpmyadmin-80-https:
      entrypoints:
        - http-8037
      rule: HostRegexp(`^twitty\.ddev\.site$`)
      
      service: "twitty-phpmyadmin-80"
      ruleSyntax: v3
      
      tls: true
      
    

  middlewares:
    twitty-redirectHttps:
      redirectScheme:
        scheme: https
        permanent: true

  services:
    twitty-web-80:
      loadbalancer:
        servers:
          - url: http://ddev-twitty-web:80
        
    twitty-web-8025:
      loadbalancer:
        servers:
          - url: http://ddev-twitty-web:8025
        
    
    
    twitty-phpmyadmin-80:
      loadbalancer:
        servers:
          - url: http://ddev-twitty-phpmyadmin:80
        
    
    

tls:
  certificates:
    - certFile: /mnt/ddev-global-cache/traefik/certs/twitty.crt
      keyFile: /mnt/ddev-global-cache/traefik/certs/twitty.key