name: ddev-twitty
networks:
    ddev_default:
        external: true
        name: ddev_default
    default:
        labels:
            com.ddev.platform: ddev
        name: ddev-twitty_default
services:
    db:
        build:
            args:
                BASE_IMAGE: ddev/ddev-dbserver-mariadb-10.11:v1.23.4
                gid: "1000"
                uid: "1000"
                username: vadgyrif
            context: /home/vadgyrif/Twitty-main/.ddev/.dbimageBuild
            dockerfile: Dockerfile
        cap_add:
            - SYS_NICE
        command: []
        container_name: ddev-twitty-db
        environment:
            COLUMNS: "80"
            DDEV_DATABASE: mariadb:10.11
            DDEV_DATABASE_FAMILY: mysql
            DDEV_HOSTNAME: twitty.ddev.site
            DDEV_PHP_VERSION: "8.2"
            DDEV_PRIMARY_URL: https://twitty.ddev.site
            DDEV_PROJECT: twitty
            DDEV_PROJECT_TYPE: php
            DDEV_ROUTER_HTTP_PORT: "80"
            DDEV_ROUTER_HTTPS_PORT: "443"
            DDEV_SITENAME: twitty
            DDEV_TLD: ddev.site
            DOCKER_IP: 127.0.0.1
            GOARCH: amd64
            GOOS: linux
            HOST_DOCKER_INTERNAL_IP: ""
            IS_DDEV_PROJECT: "true"
            LINES: "24"
            MYSQL_HISTFILE: /mnt/ddev-global-cache/mysqlhistory/twitty-db/mysql_history
            MYSQL_PWD: db
            PGDATABASE: db
            PGHOST: 127.0.0.1
            PGPASSWORD: db
            PGUSER: db
            POSTGRES_DB: db
            POSTGRES_PASSWORD: db
            POSTGRES_USER: db
            TZ: ""
            USER: vadgyrif
        healthcheck:
            interval: 1s
            retries: 70
            start_interval: 1s
            start_period: 2m0s
            timeout: 1m10s
        hostname: twitty-db
        image: ddev/ddev-dbserver-mariadb-10.11:v1.23.4-twitty-built
        labels:
            com.ddev.app-type: php
            com.ddev.approot: /home/vadgyrif/Twitty-main
            com.ddev.platform: ddev
            com.ddev.site-name: twitty
        networks:
            ddev_default: null
            default: null
        ports:
            - host_ip: 127.0.0.1
              mode: ingress
              protocol: tcp
              published: "32776"
              target: 3306
        restart: "no"
        stop_grace_period: 1m0s
        user: 1000:1000
        volumes:
            - source: database
              target: /var/lib/mysql
              type: volume
              volume:
                nocopy: true
            - bind:
                create_host_path: true
              source: /home/vadgyrif/Twitty-main/.ddev
              target: /mnt/ddev_config
              type: bind
            - bind:
                create_host_path: true
              source: /home/vadgyrif/Twitty-main/.ddev/db_snapshots
              target: /mnt/snapshots
              type: bind
            - source: ddev-global-cache
              target: /mnt/ddev-global-cache
              type: volume
              volume: {}
        working_dir: /home/vadgyrif
    phpmyadmin:
        container_name: ddev-twitty-phpmyadmin
        depends_on:
            db:
                condition: service_started
                required: true
        environment:
            HTTP_EXPOSE: 8036:80
            HTTPS_EXPOSE: 8037:80
            PMA_HOST: db
            PMA_PASSWORD: root
            PMA_PORT: "3306"
            PMA_USER: root
            UPLOAD_LIMIT: 4000M
            VIRTUAL_HOST: twitty.ddev.site
        expose:
            - "80"
        healthcheck:
            interval: 2m0s
            retries: 1
            timeout: 2s
        image: phpmyadmin:5.2.0
        labels:
            com.ddev.approot: /home/vadgyrif/Twitty-main
            com.ddev.site-name: twitty
        networks:
            ddev_default: null
            default: null
        restart: "no"
        volumes:
            - bind:
                create_host_path: true
              source: /home/vadgyrif/Twitty-main/.ddev
              target: /mnt/ddev_config
              type: bind
            - source: ddev-global-cache
              target: /mnt/ddev-global-cache
              type: volume
              volume: {}
        working_dir: /root
    web:
        build:
            args:
                BASE_IMAGE: ddev/ddev-webserver:v1.23.4
                DDEV_DATABASE: mariadb:10.11
                DDEV_PHP_VERSION: "8.2"
                gid: "1000"
                uid: "1000"
                username: vadgyrif
            context: /home/vadgyrif/Twitty-main/.ddev/.webimageBuild
            dockerfile: Dockerfile
        cap_add:
            - SYS_PTRACE
        command:
            - /pre-start.sh
        container_name: ddev-twitty-web
        environment:
            COLUMNS: "80"
            COREPACK_ENABLE_DOWNLOAD_PROMPT: "0"
            COREPACK_HOME: /mnt/ddev-global-cache/corepack
            DDEV_COMPOSER_ROOT: /var/www/html
            DDEV_DATABASE: mariadb:10.11
            DDEV_DATABASE_FAMILY: mysql
            DDEV_DOCROOT: public/
            DDEV_FILES_DIR: ""
            DDEV_FILES_DIRS: ""
            DDEV_HOSTNAME: twitty.ddev.site
            DDEV_MUTAGEN_ENABLED: "false"
            DDEV_PHP_VERSION: "8.2"
            DDEV_PRIMARY_URL: https://twitty.ddev.site
            DDEV_PROJECT: twitty
            DDEV_PROJECT_TYPE: php
            DDEV_ROUTER_HTTP_PORT: "80"
            DDEV_ROUTER_HTTPS_PORT: "443"
            DDEV_SITENAME: twitty
            DDEV_TLD: ddev.site
            DDEV_VERSION: v1.23.4
            DDEV_WEB_ENTRYPOINT: /mnt/ddev_config/web-entrypoint.d
            DDEV_WEBSERVER_TYPE: nginx-fpm
            DDEV_XDEBUG_ENABLED: "false"
            DEPLOY_NAME: local
            DOCKER_IP: 127.0.0.1
            DOCROOT: public/
            DRUSH_ALLOW_XDEBUG: "1"
            DRUSH_OPTIONS_URI: https://twitty.ddev.site
            GOARCH: amd64
            GOOS: linux
            HOST_DOCKER_INTERNAL_IP: ""
            HTTP_EXPOSE: 80:80,8025:8025
            HTTPS_EXPOSE: 443:80,8026:8025
            IS_DDEV_PROJECT: "true"
            LINES: "24"
            MYSQL_HISTFILE: /mnt/ddev-global-cache/mysqlhistory/twitty-web/mysql_history
            MYSQL_PWD: db
            NODE_EXTRA_CA_CERTS: /mnt/ddev-global-cache/mkcert/rootCA.pem
            PGDATABASE: db
            PGHOST: db
            PGPASSWORD: db
            PGUSER: db
            PHP_IDE_CONFIG: serverName=twitty.ddev.site
            SSH_AUTH_SOCK: /home/.ssh-agent/socket
            TZ: ""
            USER: vadgyrif
            VIRTUAL_HOST: twitty.ddev.site
            npm_config_cache: /mnt/ddev-global-cache/npm
        external_links:
            - ddev-router:twitty.ddev.site
        extra_hosts:
            - host.docker.internal=host-gateway
        healthcheck:
            interval: 1s
            retries: 70
            start_interval: 1s
            start_period: 2m0s
            timeout: 1m10s
        hostname: twitty-web
        image: ddev/ddev-webserver:v1.23.4-twitty-built
        labels:
            com.ddev.app-type: php
            com.ddev.approot: /home/vadgyrif/Twitty-main
            com.ddev.platform: ddev
            com.ddev.site-name: twitty
        networks:
            ddev_default: null
            default: null
        ports:
            - host_ip: 127.0.0.1
              mode: ingress
              protocol: tcp
              published: "32774"
              target: 80
            - host_ip: 127.0.0.1
              mode: ingress
              protocol: tcp
              published: "32775"
              target: 443
        restart: "no"
        user: 1000:1000
        volumes:
            - consistency: cached
              source: ../
              target: /var/www/html
              type: bind
            - bind:
                create_host_path: true
              read_only: true
              source: /home/vadgyrif/Twitty-main/.ddev
              target: /mnt/ddev_config
              type: bind
            - bind:
                create_host_path: true
              read_only: true
              source: /home/vadgyrif/Twitty-main/.ddev/xhprof
              target: /usr/local/bin/xhprof
              type: bind
            - source: ddev-global-cache
              target: /mnt/ddev-global-cache
              type: volume
              volume: {}
            - source: ddev-ssh-agent_socket_dir
              target: /home/.ssh-agent
              type: volume
              volume: {}
        working_dir: /var/www/html/
volumes:
    database:
        external: true
        name: twitty-mariadb
    ddev-global-cache:
        external: true
        name: ddev-global-cache
    ddev-ssh-agent_socket_dir:
        external: true
        name: ddev-ssh-agent_socket_dir
